[package]
name = "chip_8_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19.0"
crossterm = "0.25.0"
rand = "0.8.5"
clap = { version = "4.0.8", features = ["derive"] }
